object Versions {
    const val compile_sdk = 29
    const val build_tools = "29.0.2"
    const val min_sdk = 19
    const val target_sdk = 29
    const val version_code = 1
    const val version_name = "1.0"
    const val kotlin = "1.3.50"
    const val appcompat_version = "1.1.0"
    const val support_lib = "28.0.0"
    const val constraint_lib = "1.1.2"
    const val material_design = "1.1.0"
    const val recycler_view = "1.1.0"
    const val junit_lib = "4.12"
    const val test_lib = "1.1.1"
    const val core_ktx = "1.0.2"
    const val multidex = "2.0.1"
    const val espresso_core_lib = "3.2.0"
    const val qumi = "2.0.0-alpha05"
    const val okhttp3_logging = "4.4.0"
    const val gson = "2.8.6"
    const val okhttp3 = "4.4.0"
    const val retrofit2 = "2.7.2"
    const val rxjava2 = "2.2.19"
    const val rxandroid = "2.1.1"
    const val brvah = "3.0.1"
    const val immersionBar = "3.0.0-beta04"
    const val immersion_components = "3.0.0-beta04"
    const val glide = "4.11.0"
    const val smartRefresh = "1.1.2"
    const val agentWeb = "4.1.3"
    const val picture_selector = "2.4.9"
    const val lottieVersion = "3.4.0"
}

object Package {
    const val application_Id = "com.df.playandroid"
}

object Libs {
    const val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat_version}"
    const val constraint = "androidx.constraintlayout:constraintlayout:${Versions.constraint_lib}"
    const val junit = "junit:junit:${Versions.junit_lib}"
    const val test_runner = "androidx.test.ext:junit:${Versions.test_lib}"
    const val espresso_core = "androidx.test.espresso:espresso-core:${Versions.espresso_core_lib}"
    const val core_ktx = "androidx.core:core-ktx:${Versions.core_ktx}"
    const val multidex = "androidx.multidex:multidex:${Versions.multidex}"
    const val material_design = "com.google.android.material:material:${Versions.material_design}"
    const val recycler_view = "androidx.recyclerview:recyclerview:${Versions.recycler_view}"
    const val qmui = "com.qmuiteam:qmui:${Versions.qumi}"
    const val okhttp3_logging = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp3_logging}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val okhttp3 = "com.squareup.okhttp3:okhttp:${Versions.okhttp3}"
    const val retrofit2 = "com.squareup.retrofit2:retrofit:${Versions.retrofit2}"
    const val retrofit2_converters = "com.squareup.retrofit2:retrofit-converters:${Versions.retrofit2}"
    const val retrofit2_converter_gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit2}"
    const val retrofit2_adapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit2}"
    const val rxjava2 = "io.reactivex.rxjava2:rxjava:${Versions.rxjava2}"
    const val rxandroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroid}"
    const val BRVAH = "com.github.CymChad:BaseRecyclerViewAdapterHelper:${Versions.brvah}"
    const val ImmersionBar = "com.gyf.immersionbar:immersionbar:${Versions.immersionBar}"
    const val Immersion_components = "com.gyf.immersionbar:immersionbar-components:${Versions.immersion_components}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val smartRefresh = "com.scwang.smartrefresh:SmartRefreshLayout:${Versions.smartRefresh}"
    const val agentWeb = "com.just.agentweb:agentweb:${Versions.agentWeb}"
    const val picture_selector = "com.github.LuckSiege.PictureSelector:picture_library:v${Versions.picture_selector}"
    const val lottie = "com.airbnb.android:lottie:${Versions.lottieVersion}"
}